// Code generated by protoc-gen-go. DO NOT EDIT.
// source: demo/example.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	demo/example.proto

It has these top-level messages:
	Element
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Element_Attribute_AttributeType int32

const (
	Element_Attribute_STRING  Element_Attribute_AttributeType = 0
	Element_Attribute_NUMBER  Element_Attribute_AttributeType = 1
	Element_Attribute_BOOLEAN Element_Attribute_AttributeType = 2
	Element_Attribute_NODE    Element_Attribute_AttributeType = 3
)

var Element_Attribute_AttributeType_name = map[int32]string{
	0: "STRING",
	1: "NUMBER",
	2: "BOOLEAN",
	3: "NODE",
}
var Element_Attribute_AttributeType_value = map[string]int32{
	"STRING":  0,
	"NUMBER":  1,
	"BOOLEAN": 2,
	"NODE":    3,
}

func (x Element_Attribute_AttributeType) String() string {
	return proto.EnumName(Element_Attribute_AttributeType_name, int32(x))
}
func (Element_Attribute_AttributeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0, 0}
}

type Element struct {
	Name       string               `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Attributes []*Element_Attribute `protobuf:"bytes,2,rep,name=attributes" json:"attributes,omitempty"`
}

func (m *Element) Reset()                    { *m = Element{} }
func (m *Element) String() string            { return proto.CompactTextString(m) }
func (*Element) ProtoMessage()               {}
func (*Element) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Element) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Element) GetAttributes() []*Element_Attribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type Element_Attribute struct {
	Name     string                          `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Type     Element_Attribute_AttributeType `protobuf:"varint,2,opt,name=type,enum=demo.Element_Attribute_AttributeType" json:"type,omitempty"`
	Value    string                          `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
	Children []*Element_Attribute            `protobuf:"bytes,4,rep,name=children" json:"children,omitempty"`
}

func (m *Element_Attribute) Reset()                    { *m = Element_Attribute{} }
func (m *Element_Attribute) String() string            { return proto.CompactTextString(m) }
func (*Element_Attribute) ProtoMessage()               {}
func (*Element_Attribute) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Element_Attribute) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Element_Attribute) GetType() Element_Attribute_AttributeType {
	if m != nil {
		return m.Type
	}
	return Element_Attribute_STRING
}

func (m *Element_Attribute) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Element_Attribute) GetChildren() []*Element_Attribute {
	if m != nil {
		return m.Children
	}
	return nil
}

func init() {
	proto.RegisterType((*Element)(nil), "demo.Element")
	proto.RegisterType((*Element_Attribute)(nil), "demo.Element.Attribute")
	proto.RegisterEnum("demo.Element_Attribute_AttributeType", Element_Attribute_AttributeType_name, Element_Attribute_AttributeType_value)
}

func init() { proto.RegisterFile("demo/example.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4a, 0x49, 0xcd, 0xcd,
	0xd7, 0x4f, 0xad, 0x48, 0xcc, 0x2d, 0xc8, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0x01, 0x89, 0x29, 0xed, 0x63, 0xe2, 0x62, 0x77, 0xcd, 0x49, 0xcd, 0x4d, 0xcd, 0x2b, 0x11, 0x12,
	0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x85,
	0xcc, 0xb9, 0xb8, 0x12, 0x4b, 0x4a, 0x8a, 0x32, 0x93, 0x4a, 0x4b, 0x52, 0x8b, 0x25, 0x98, 0x14,
	0x98, 0x35, 0xb8, 0x8d, 0xc4, 0xf5, 0x40, 0x5a, 0xf5, 0xa0, 0xda, 0xf4, 0x1c, 0x61, 0xf2, 0x41,
	0x48, 0x4a, 0xa5, 0x9e, 0x32, 0x72, 0x71, 0xc2, 0x65, 0xb0, 0x1a, 0x6d, 0xc9, 0xc5, 0x52, 0x52,
	0x59, 0x90, 0x2a, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x67, 0xa4, 0x8a, 0xc3, 0x50, 0x04, 0x2b, 0xa4,
	0xb2, 0x20, 0x35, 0x08, 0xac, 0x45, 0x48, 0x84, 0x8b, 0xb5, 0x2c, 0x31, 0xa7, 0x34, 0x55, 0x82,
	0x19, 0x6c, 0x1e, 0x84, 0x23, 0x64, 0xcc, 0xc5, 0x91, 0x9c, 0x91, 0x99, 0x93, 0x52, 0x94, 0x9a,
	0x27, 0xc1, 0x82, 0xdf, 0xa5, 0x70, 0x85, 0x4a, 0x76, 0x5c, 0xbc, 0x28, 0x36, 0x08, 0x71, 0x71,
	0xb1, 0x05, 0x87, 0x04, 0x79, 0xfa, 0xb9, 0x0b, 0x30, 0x80, 0xd8, 0x7e, 0xa1, 0xbe, 0x4e, 0xae,
	0x41, 0x02, 0x8c, 0x42, 0xdc, 0x5c, 0xec, 0x4e, 0xfe, 0xfe, 0x3e, 0xae, 0x8e, 0x7e, 0x02, 0x4c,
	0x42, 0x1c, 0x5c, 0x2c, 0x7e, 0xfe, 0x2e, 0xae, 0x02, 0xcc, 0x4e, 0x2c, 0x51, 0x4c, 0x05, 0x49,
	0x49, 0x6c, 0xe0, 0x30, 0x35, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xf6, 0x2d, 0x37, 0x94, 0x69,
	0x01, 0x00, 0x00,
}
